name: webrtc_conference
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  collection: ^1.15.0
  flutter_svg: ^0.23.0
  flutter_svg_provider: ^0.1.11

  searchable_dropdown: ^1.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  http: ^0.13.4
  faker: ^2.0.0
  provider: ^6.0.2
  crypto: ^3.0.1
  flutter_secure_storage: ^5.0.2
  copy_with_extension: ^4.0.0
  package_info: ^2.0.2
  equatable: ^2.0.3
  version: ^2.0.0
  bot_toast: ^4.0.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  state_persistence: ^0.1.0
  loading_more_list: ^4.1.0
  pull_to_refresh_notification: ^2.3.0
  extended_nested_scroll_view: ^5.0.0
  dotted_line: ^3.1.0
  cached_network_image: ^3.2.0
  grouped_list: ^4.2.0
  tuple: ^2.0.0
  url_launcher: ^6.0.20
#  extended_nested_scroll_view:
#    git: git://github.com/comerc/extended_nested_scroll_view.git
  font_awesome_flutter: ^9.2.0

  flutter_bloc: ^8.0.0
  expandable: ^5.0.1
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  copy_with_extension_gen: ^4.0.0
  build_runner: ^2.1.7
  lints: ^1.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
  assets:
    - assets/images/welcoming-dinner.jpeg
    - assets/images/first-day-dinner.jpeg
    - assets/images/farewell-dinner.jpeg
    - assets/images/air_transport.jpeg
    - assets/images/airport.jpeg
    - assets/images/Login_planet.png
    - assets/images/Login_Background.png
    - assets/images/Login_Background@2x.png
    - assets/images/Login_Background.svg
    - assets/images/planet.png
    - assets/images/ADSD_logo.png
    - assets/images/home_background.png
    - assets/images/agenda_background.png
    - assets/images/ADSD_Logo_small.png
    - assets/images/Agenda.svg
    - assets/images/home_profile_avatar.jpeg
    - assets/images/key_invitation.svg
    - assets/images/Council_partner.png
    - assets/images/InfoStrategic.png
    - assets/images/Office_partner.png
    - assets/images/Diplomatic_partner.png
    - assets/images/GSCP_partner.png
    - assets/images/map.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
